// *************************************   Conversion
// ........................... string to number
console.log(Number('3.14'));
// .....................
console.log(Number(''));
// .....................
console.log(Number('  '));
// .....................
console.log(Number('vahid123'));
// .....................
console.log(Number('vahid 123'));
var a='vahid';
console.log(Number(a));
// .....................
var a='33';
console.log(Number(a));
4// .....................
var a='33';
console.log(Number(a));
// .....................
var a='33';
console.log(Number(a));
// .....................
var a='33';
console.log(Number(a));